keys:
  - &primary age14r4f8cpf7qslkdwu2v4lus5xfdzdy4dwql8xvxxkxhs230rdac3sjgexdz
creation_rules:
  - path_regex: hosts/ns-alpha/nixos/secrets/config.py$
    key_groups:
    - age:
      - *primary
  - path_regex: hosts/ns-alpha/nixos/secrets/Caddyfile$
    key_groups:
    - age:
      - *primary
  - path_regex: hosts/ns-alpha/nixos/secrets/open-webui.env$
    key_groups:
    - age:
      - *primary
  - path_regex: hosts/ns-alpha/nixos/secrets/searx$
    key_groups:
    - age:
      - *primary
  - path_regex: hosts/ns-alpha/nixos/secrets/litellm.yaml$
    key_groups:
    - age:
      - *primary
  - path_regex: hosts/ns-alpha/nixos/secrets/litellm.env$
    key_groups:
    - age:
      - *primary
  - path_regex: hosts/ns-alpha/nixos/secrets/litellm.postgres.env$
    key_groups:
    - age:
      - *primary
  - path_regex: hosts/ns-alpha/nixos/secrets/litellm.prometheus.yaml$
    key_groups:
    - age:
      - *primary
  - path_regex: hosts/ns-beta/nixos/secrets/Caddyfile$
    key_groups:
    - age:
      - *primary
  - path_regex: hosts/ns-beta/nixos/secrets/remnawave.json$
    key_groups:
    - age:
      - *primary
  - path_regex: hosts/ns-gamma/nixos/secrets/hysteria.yaml$
    key_groups:
    - age:
      - *primary
  - path_regex: hosts/ns-beta/nixos/secrets/xray.json$
    key_groups:
    - age:
      - *primary